[tool.poetry]
name = "acache"
version = "0.1.0"
description = ""
authors = ["Щиголь Алексей <ashchigol@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cachetools = "^5.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
